---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Semaphore
  ansible.builtin.systemd_service:
    name: semaphore.service
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
