---
all:
  children:
    remnawave_nodes:
      hosts:
        de-fra-01:
          ansible_host: 203.0.113.10
          node_id: de_01
          node_name: DE-01
          node_public_ip: 203.0.113.10
          node_country: DE
          provider: example-provider
          region: de-fra
          zone: fra-1
          selfsteal_domain: node-de-01.example.com
          profile_name: DE-01
          internal_squad_name: Default

